//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Players4Match = new HashSet<Players4Match>();
        }
    
        public int Id { get; set; }
        public int HomeId { get; set; }
        public int AwayId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PredictedScoreId { get; set; }
        public Nullable<int> RealScoreId { get; set; }
        public string Referee { get; set; }
    
        public virtual PredictedScore PredictedScore { get; set; }
        public virtual RealScore RealScore { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Players4Match> Players4Match { get; set; }
    }
}
