//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealScore()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HomeGoals { get; set; }
        public Nullable<int> AwayGoals { get; set; }
        public Nullable<int> HomeShots { get; set; }
        public Nullable<int> AwayShots { get; set; }
        public Nullable<int> HomeShotsOnTarget { get; set; }
        public Nullable<int> AwayShotsOnTarget { get; set; }
        public Nullable<int> HomeCorners { get; set; }
        public Nullable<int> AwayCorners { get; set; }
        public Nullable<int> HomeOffsides { get; set; }
        public Nullable<int> AwayOffsides { get; set; }
        public Nullable<int> HomeFouls { get; set; }
        public Nullable<int> AwayFouls { get; set; }
        public Nullable<int> HomeYellowCards { get; set; }
        public Nullable<int> AwayYellowCards { get; set; }
        public Nullable<int> HomeRedCards { get; set; }
        public Nullable<int> AwayRedCards { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
    }
}
